### ISSUE TITLE
Добавить token приложения.

### ISSUE THREAD

**Issue by vadimsmirnovnsk** [teanet/Nazabore#20]

**Comment by romanyanke** [comment]
непонятно ничего

**Comment by vadimsmirnovnsk** [comment]
@romanyanke Ром, нам нужно сделать так, чтобы нам в API кто угодно не мог запушить миллиарды говносообщений. 
Сейчас любой может попарсить запросы, понять формат методов и нагенерить нам туда говна.
Но чтобы такого не произошло, на все методы мы добавим параметр app_token: "длинный хеш", который захардкодим в приложении. И если этот хеш есть, то считаем, что обращение к API корректное, если нет - то это кто-то неизвестный ломится.

Это, естессно, не будет работать без https.

**Comment by vadimsmirnovnsk** [comment]
Добавил сертификаты на сервак, и сконфигурял nginx. 
Теперь api.nazabore.xyz работает по https.

Также сертификаты сгенерены на:

```
api.nazabore.xyz
nazabore.xyz
www.nazabore.xyz
reklama.nazabore.xyz
```
