### ISSUE TITLE
Ограничивать карту масштабом в 2км

### ISSUE THREAD

**Issue by romanyanke** [teanet/Nazabore#40]
Поскольку не видно заборов дальше, не надо показывать всю карту

**Comment by vadimsmirnovnsk** [comment]
Мне кажется, что круг видимости лучше.
Вдруг у нас будут специальные заборы, которые можно видеть везде. 
На этом можно продуктовые фичи какие-нить придумать, типа пушить сообщение с забора пользователю, типа именно вот здесь произошло что-то.

**Comment by romanyanke** [comment]
оокей, можно попробовать кругом сделать

**Comment by vadimsmirnovnsk** [comment]
Wont fix.
Закрываем, делаем круг видимости с радиусом.
