### ISSUE TITLE
Добавить столб "вальхаллы" для не включивших локацию.

### ISSUE THREAD

**Issue by vadimsmirnovnsk** [teanet/Nazabore#53]
- добавить на нулевой столб ОБЪЯВЛЕНИЕ "Здесь сообщения всех тех, кто забыл разрешить приложению знать геолокацию.\nThis is the place for fluffy people that have forgotten to switch on fetching their location."
- сделать так, чтобы с сервера возвращался нулевой столб (при lon и lat равных 0)
- во второй итерации сделать это слоем (из одного столба).

**Comment by romanyanke** [comment]
бэкенд готов

**Comment by vadimsmirnovnsk** [comment]
Вроде всё готово.
