### ISSUE TITLE
Добавить на сервер метод user по userId

### ISSUE THREAD

**Issue by vadimsmirnovnsk** [teanet/Nazabore#57]
`GET */user?id="uiserId"`

Возвращает:

```
{
    ...
    id = "userId",
    visibleRange = "unsigned integer (количество метров, default = 2000)" 
    ...
}
```

Здесь будет прилетать `userId` в хедере, и/или в `query`. 
- Если в `query` не прилетает, то возвращаем `userInfo` для `userId`, переданного в хидере.
- Если прилетает, то возвращаем `userInfo` для `userId`, переданного в `query`.

**Comment by romanyanke** [comment]
помни: тут query.id важней из хедеров
